### PR TITLE
Write the context proposal

### PR DESCRIPTION
**Pull request by nplasterer**
Fix up context writing.

### CODE REVIEW

**Review by cameronvoell — APPROVED** [review]
I see libxmtp tests passing 👍

**Review by neekolas — APPROVED** [review]
Approving to unblock.

Just to clarify, all these changes also exist in openmls main?

**Comment by nplasterer** [comment]
Yep there is just one function that @cameronvoell added for group mutable metadata which hasn't been contributed back to openMLS main. (which was where the bug was) But now that it's working I think we can feel confident in contributing that back.

**Comment by nplasterer** [comment]
Contributed the fix back here: https://github.com/openmls/openmls/pull/1580

**Pull request merged**
